export const ADD_USER_INTO_LIST = "ADD_USER_INTO_LIST";
export const GET_USER_LIST = "GET_USER_LIST";
export const REMOVE_USER_FROM_LIST = "REMOVE_USER_FROM_LIST";
export const EDIT_SELECTED_USER = "EDIT_SELECTED_USER";
// Repository Lists
export const GET_REPOSITORY_LIST = "GET_REPOSITORY_LIST";
export const SEARCH_REPOSITORY_FROM_LIST = "SEARCH_REPOSITORY_FROM_LIST";